"""Generate the Work index and detail pages from YYYY/works.json files."""

import json
import re
from html import escape
from pathlib import Path
from urllib.parse import quote


ROOT = Path(__file__).resolve().parent


def page(title, content, prefix=""):
    html = f'''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{escape(title)} — Matthew Burgess</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Urbanist:wght@400&amp;display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{prefix}styles.css">
</head>
<body>
  <!-- Generated by build_site.py. Edit the year's works.json to update content. -->
  <header class="site-header">
    <a class="site-name" href="{prefix}index.html">Matthew Burgess</a>
    <nav class="page-nav" aria-label="Main navigation">
      <a href="{prefix}about.html">About</a>
      <a href="{prefix}portfolio.html" aria-current="page">Work</a>
      <a href="{prefix}artist-statement.html">Artist statement</a>
      <a href="{prefix}contact.html">Contact</a>
    </nav>
  </header>
{content}
</body>
</html>
'''
    return "\n".join(line.rstrip() for line in html.splitlines()) + "\n"


def read_years(root):
    years = []
    for folder in sorted(root.iterdir(), reverse=True):
        if not folder.is_dir() or not re.fullmatch(r"\d{4}", folder.name):
            continue
        source = folder / "works.json"
        if not source.exists():
            continue
        data = json.loads(source.read_text(encoding="utf-8"))
        if not isinstance(data, dict) or not isinstance(data.get("works"), list):
            raise ValueError(f'{source}: expected an object containing a "works" array')
        seen = set()
        for work in data["works"]:
            if not isinstance(work, dict):
                raise ValueError(f"{source}: each work must be an object")
            work_id = work.get("id", "")
            if not isinstance(work_id, str) or not re.fullmatch(folder.name + r"_[A-Za-z0-9_-]+", work_id):
                raise ValueError(f"{source}: invalid work ID {work_id!r}")
            if work_id in seen:
                raise ValueError(f"{source}: duplicate work ID {work_id}")
            seen.add(work_id)
            for field in ("title", "description", "dimensions"):
                if not isinstance(work.get(field, ""), str):
                    raise ValueError(f"{source}: {work_id} {field} must be text")
            images = work.get("images")
            if not isinstance(images, list) or not images:
                raise ValueError(f"{source}: {work_id} needs at least one image")
            for filename in images:
                if (not isinstance(filename, str) or Path(filename).name != filename
                        or not (folder / filename).is_file()):
                    raise ValueError(f"{source}: {work_id} image not found in its year folder: {filename!r}")
        if data["works"]:
            years.append((folder.name, data["works"]))
    return years


def build(root=ROOT):
    # Validate all source files before changing any generated pages.
    years = read_years(root)
    sections = []
    details = {}
    for year, works in years:
        cards = []
        for work in works:
            work_id = work["id"]
            title = work.get("title", "").strip()
            label = title or "Untitled"
            thumbnail = quote(f'{year}/{work["images"][0]}')
            caption = f'<span class="work-title">{escape(title)}</span>' if title else ""
            cards.append(f'''        <a class="work-card" href="work/{work_id}.html" aria-label="View {escape(label)}, {year}">
          <img src="{thumbnail}" alt="{escape(label)}, {year}" loading="lazy">
          {caption}
        </a>''')

            metadata = []
            description = work.get("description", "").strip()
            dimensions = work.get("dimensions", "").strip()
            if description:
                metadata.append(f'<p class="work-description">{escape(description)}</p>')
            if dimensions:
                metadata.append(f'<dl class="work-dimensions"><dt>Dimensions</dt><dd>{escape(dimensions)}</dd></dl>')
            images = []
            for number, filename in enumerate(work["images"], start=1):
                image_url = "../" + quote(f"{year}/{filename}")
                loading = ' loading="lazy"' if number > 1 else ""
                images.append(f'''        <button class="detail-image" type="button" aria-haspopup="dialog" aria-controls="gallery-lightbox" aria-expanded="false" aria-label="Enlarge {escape(label)}, image {number}">
          <img src="{image_url}" alt="{escape(label)}, {year} — view {number}"{loading}>
        </button>''')
            details[f"work/{work_id}.html"] = page(label, f'''  <main class="work-detail">
    <a class="detail-back" href="../portfolio.html#year-{year}">&larr; Work / {year}</a>
    <div class="detail-layout">
      <section class="work-info" aria-labelledby="work-title">
        <p class="work-year">{year}</p>
        <h1 id="work-title">{escape(label)}</h1>
        {''.join(metadata)}
      </section>
      <div class="detail-images">
{chr(10).join(images)}
      </div>
    </div>
  </main>
  <dialog class="lightbox" id="gallery-lightbox" aria-label="Enlarged artwork">
    <button class="lightbox-close" type="button" autofocus>Close &times;</button>
    <button class="lightbox-image" type="button" aria-label="Close enlarged image">
      <img alt="">
    </button>
  </dialog>
  <script src="../gallery.js" defer></script>''', prefix="../")

        sections.append(f'''    <section class="year-block" id="year-{year}" aria-labelledby="heading-{year}">
      <h2 id="heading-{year}">{year}</h2>
      <div class="work-grid year-grid">
{chr(10).join(cards)}
      </div>
    </section>''')

    content = "\n".join(sections) or '    <p>Selected work coming soon.</p>'
    outputs = {"portfolio.html": page("Work", f'''  <main class="work-index">
    <h1>Work</h1>
{content}
  </main>'''), **details}
    for name, html in outputs.items():
        destination = root / name
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(html, encoding="utf-8")
    return len(years), len(details)


if __name__ == "__main__":
    year_count, work_count = build()
    print(f"Generated Work page: {year_count} year(s), {work_count} artwork page(s).")
